
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: '$(Build.Repository.Name)'
            publishLocation: 'Container'
  - stage: docker  
    jobs:
      - job: docker
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerHub'
            repository: 'accountregistration'
            command: 'buildAndPush'
            Dockerfile: '$(Build.ArtifactStagingDirectory)/dockerfile'
            buildContext: '$(Build.ArtifactStagingDirectory)'