
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: '$(Build.Repository.Name)'
            publishLocation: 'Container'
  - stage: Docker  
    displayName: docker image build and push
    jobs:
      - job: docker
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
           # downloadType: 'single'
            downloadPath: '$(Build.ArtifactStagingDirectory)'

        - script: |
                 cp $(Build.ArtifactStagingDirectory)/sreeni-sanni/accountRegistrationAPI/accountRegistrationAPI-0.0.1.jar $(Build.SourcesDirectory)
           
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerHub'
            repository: 'sanniboena/accountregistration'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: '$(Build.BuildId)'
            buildContext: '**'
  - stage: deploy
    displayName: helm deploy
    jobs:
      - job: PublishPipelineArtifact
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              publishLocation: 'pipeline'
          - task: HelmInstaller@0
            inputs:
              helmVersion: '2.14.1'
              installKubectl: true
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'aks'
              command: 'upgrade'
              chartType: 'Name'
              chartName: '$(Build.SourcesDirectory)'
              releaseName: 'accountchart'
              valueFile: '$(Build.SourcesDirectory)/accountChart/values.yaml'