
trigger:
- main

variables:
  - name: version
    value: $(build.buildid)

pool: dockerAgent


stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: '$(Build.Repository.Name)'
            publishLocation: 'Container'
  - stage: Docker  
    displayName: Docker Build
    jobs:
      - job: BuildAndPush
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
           # downloadType: 'single'
            downloadPath: '$(Build.ArtifactStagingDirectory)'

        - script: |
                 cp $(Build.ArtifactStagingDirectory)/sreeni-sanni/accountRegistrationAPI/accountRegistrationAPI-0.0.1.jar $(Build.SourcesDirectory)
           
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-accountapi'
            repository: 'accountapi'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: '$(version)'
 