
trigger:
- main

variables:
  - name: version
    value: $(build.buildid)

pool: 
  vmImage: ubuntu-latest


stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: '$(Build.Repository.Name)'
            publishLocation: 'Container'
  - stage: Docker  
    displayName: Docker Build
    jobs:
      - job: BuildAndPush
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
           # downloadType: 'single'
            downloadPath: '$(Build.ArtifactStagingDirectory)'

        - script: |
                 cp $(Build.ArtifactStagingDirectory)/sreeni-sanni/accountRegistrationAPI/accountRegistrationAPI-0.0.1.jar $(Build.SourcesDirectory)
                 
        - task: Docker@2
          inputs:
            containerRegistry: 'azuredocker'
            repository: 'accountapi'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
 
  - stage: CD
    displayName: Helm Deploy
    jobs:
      - job: PublishPipelineArtifact
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'

          - task: CmdLine@2
            inputs:
             script: |
                   cd $(Build.SourcesDirectory)
                   ls

      - job: HelmInstallUpgrade
        steps:      
          
          - task: HelmInstaller@0
            inputs:
              helmVersion: 'latest'
              installKubectl: false
          - task: HelmDeploy@0
            inputs:
             command: 'package'
             chartPath: '$(Build.SourcesDirectory)/accountchart'
             chartVersion: $(Build.Id)
             arguments: '--app-version $(Build.Id)'
          - task: CmdLine@2
            inputs:
             script: |
                   cd $(Build.SourcesDirectory)
                   ls
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-sreeni'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az acr helm push $(System.ArtifactsDirectory)/accountchart $(Build.Id).tgz --name $(accountapi);'
                    
              
          
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'accountapi-aks'
              namespace: 'default'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Build.SourcesDirectory)/accountchart'
              releaseName: 'account-chart'
              overrideValues: 'image.tag=$(version)'
              valueFile: '$(Build.SourcesDirectory)/accountchart/values.yaml'
              waitForExecution: true
              