version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    
    volumes:
    - ./data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sreeni575@
      POSTGRES_DB: customerInformation
      PGUSER: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      
  accountregister:
    depends_on:
      db:
       condition: service_healthy
    build: ./
    ports:
     - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customerInformation?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Sreeni575@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  
    
     